CREATE TABLE consumer_users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED','LOCKED')),
    email_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (length(email) BETWEEN 3 AND 320),
    CHECK (length(password_hash) BETWEEN 20 AND 1024)
);
CREATE UNIQUE INDEX uq_consumer_users_email_ci ON consumer_users(lower(email));

INSERT INTO consumer_users(user_id,email,password_hash,status,created_at,updated_at)
SELECT user_id,email,password_hash,status,created_at,updated_at
FROM webmaster_users
ON CONFLICT(user_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('consumer_users','user_id'),
    GREATEST(COALESCE((SELECT max(user_id) FROM consumer_users),0),1),
    true
);

ALTER TABLE webmaster_users ADD COLUMN consumer_user_id BIGINT;
UPDATE webmaster_users SET consumer_user_id=user_id WHERE consumer_user_id IS NULL;
ALTER TABLE webmaster_users ALTER COLUMN consumer_user_id SET NOT NULL;
ALTER TABLE webmaster_users
    ADD CONSTRAINT fk_webmaster_users_consumer
    FOREIGN KEY(consumer_user_id) REFERENCES consumer_users(user_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX uq_webmaster_users_consumer ON webmaster_users(consumer_user_id);

CREATE TABLE consumer_sessions (
    session_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES consumer_users(user_id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(token_hash)=32),
    csrf_hash BYTEA NOT NULL CHECK (octet_length(csrf_hash)=32),
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX idx_consumer_sessions_user ON consumer_sessions(user_id,expires_at DESC);
CREATE INDEX idx_consumer_sessions_active ON consumer_sessions(expires_at,session_id) WHERE revoked_at IS NULL;

CREATE TABLE consumer_auth_tokens (
    token_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES consumer_users(user_id) ON DELETE CASCADE,
    purpose TEXT NOT NULL CHECK (purpose IN ('EMAIL_VERIFY','PASSWORD_RESET')),
    token_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(token_hash)=32),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX idx_consumer_auth_tokens_user ON consumer_auth_tokens(user_id,purpose,created_at DESC);
CREATE INDEX idx_consumer_auth_tokens_active ON consumer_auth_tokens(expires_at) WHERE used_at IS NULL;

CREATE TABLE consumer_security_events (
    event_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES consumer_users(user_id) ON DELETE SET NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('REGISTER','LOGIN_OK','LOGIN_FAILED','LOGOUT','SESSION_REVOKED','EMAIL_VERIFY_ISSUED','EMAIL_VERIFIED','PASSWORD_RESET_ISSUED','PASSWORD_RESET','ACCOUNT_DISABLED')),
    details JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details)='object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_consumer_security_events_user ON consumer_security_events(user_id,created_at DESC,event_id DESC);
CREATE INDEX idx_consumer_security_events_time ON consumer_security_events(created_at DESC,event_id DESC);
