package readiness

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

var commitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)
var sha256Pattern = regexp.MustCompile(`^[0-9a-f]{64}$`)

type Check struct { Name string `json:"name"`; Pass bool `json:"pass"`; Detail string `json:"detail"` }
type Report struct { Ready bool `json:"ready"`; GitCommit string `json:"git_commit"`; ReleaseVersion string `json:"release_version"`; ExpectedSchema int64 `json:"expected_schema"`; AppliedSchema int64 `json:"applied_schema"`; CheckedAt time.Time `json:"checked_at"`; Checks []Check `json:"checks"` }
type Gate struct { DB *pgxpool.Pool; ExpectedVersions []int64; GitCommit string; ReleaseVersion string; InternetMail bool; MailDomain string; MailSelector string; Now func() time.Time }

func (g Gate) Evaluate(ctx context.Context) (Report, error) {
	if g.DB==nil{return Report{},errors.New("readiness database is not initialized")};if len(g.ExpectedVersions)==0{return Report{},errors.New("expected migration versions are required")};if !commitPattern.MatchString(g.GitCommit){return Report{},errors.New("git commit must be a lowercase 40-character SHA")};g.ReleaseVersion=strings.TrimSpace(g.ReleaseVersion);if len(g.ReleaseVersion)<1||len(g.ReleaseVersion)>128||strings.IndexFunc(g.ReleaseVersion,func(r rune)bool{return r<0x20||r==0x7f})>=0{return Report{},errors.New("release version is invalid")};if g.InternetMail&&(strings.TrimSpace(g.MailDomain)==""||strings.TrimSpace(g.MailSelector)==""){return Report{},errors.New("mail domain and DKIM selector are required when Internet Mail is enabled")}
	now:=time.Now().UTC();if g.Now!=nil{now=g.Now().UTC()};expected:=append([]int64(nil),g.ExpectedVersions...);sort.Slice(expected,func(i,j int)bool{return expected[i]<expected[j]});report:=Report{Ready:true,GitCommit:g.GitCommit,ReleaseVersion:g.ReleaseVersion,ExpectedSchema:expected[len(expected)-1],CheckedAt:now};add:=func(name string,pass bool,detail string){report.Checks=append(report.Checks,Check{Name:name,Pass:pass,Detail:detail});if !pass{report.Ready=false}}
	applied,err:=g.appliedVersions(ctx);if err!=nil{return Report{},fmt.Errorf("read applied migrations: %w",err)};if len(applied)>0{report.AppliedSchema=applied[len(applied)-1]};missing,unexpected:=diffVersions(expected,applied);add("migrations_exact",len(missing)==0&&len(unexpected)==0,fmt.Sprintf("missing=%v unexpected=%v",missing,unexpected))
	releasePass,releaseDetail,preflightAt,err:=g.releaseCandidate(ctx,report.ExpectedSchema);if err!=nil{return Report{},err};add("release_manifest",releasePass,releaseDetail)
	for _,kind:=range []string{"BUILD_UNIT","INTEGRATION","FRESH_INSTALL","UPGRADE","BROWSER_SMOKE","SECURITY_REGRESSION","EDGE_TLS_PROXY"}{var notBefore *time.Time;if evidenceRequiresPostPreflight(kind){notBefore=preflightAt};pass,detail,err:=g.evidence(ctx,kind,report.ExpectedSchema,now,notBefore);if err!=nil{return Report{},err};add("evidence_"+kind,pass,detail)}
	qualityPass,qualityDetail,err:=g.quality(ctx,now,report.ExpectedSchema);if err!=nil{return Report{},err};add("quality_gate",qualityPass,qualityDetail)
	capacityPass,capacityDetail,err:=g.capacity(ctx,now,report.ExpectedSchema);if err!=nil{return Report{},err};add("capacity_1m",capacityPass,capacityDetail)
	backupPass,backupDetail,err:=g.recovery(ctx,"BACKUP",report.ExpectedSchema,now);if err!=nil{return Report{},err};add("recovery_backup",backupPass,backupDetail)
	restorePass,restoreDetail,err:=g.recovery(ctx,"RESTORE",report.ExpectedSchema,now);if err!=nil{return Report{},err};add("recovery_restore",restorePass,restoreDetail)
	pairPass,pairDetail,err:=g.recoveryPair(ctx,report.ExpectedSchema);if err!=nil{return Report{},err};add("recovery_same_artifact",pairPass,pairDetail)
	pressurePass,pressureDetail,err:=g.resourcePressure(ctx,now);if err!=nil{return Report{},err};add("resource_pressure",pressurePass,pressureDetail)
	if g.InternetMail{mtaPass,mtaDetail,err:=g.evidence(ctx,"MTA_FLOW",report.ExpectedSchema,now,preflightAt);if err!=nil{return Report{},err};add("evidence_MTA_FLOW",mtaPass,mtaDetail);dnsPass,dnsDetail,err:=g.mailDNS(ctx,now,strings.ToLower(strings.TrimSpace(g.MailDomain)),strings.TrimSpace(g.MailSelector));if err!=nil{return Report{},err};add("mail_dns",dnsPass,dnsDetail)}
	return report,nil
}

func (g Gate) appliedVersions(ctx context.Context)([]int64,error){rows,err:=g.DB.Query(ctx,`SELECT version FROM schema_migrations ORDER BY version`);if err!=nil{return nil,err};defer rows.Close();out:=[]int64{};for rows.Next(){var v int64;if err:=rows.Scan(&v);err!=nil{return nil,err};out=append(out,v)};return out,rows.Err()}
func diffVersions(expected,applied []int64)(missing,unexpected []int64){e:=map[int64]struct{}{};a:=map[int64]struct{}{};for _,v:=range expected{e[v]=struct{}{}};for _,v:=range applied{a[v]=struct{}{}};for _,v:=range expected{if _,ok:=a[v];!ok{missing=append(missing,v)}};for _,v:=range applied{if _,ok:=e[v];!ok{unexpected=append(unexpected,v)}};return}
func (g Gate) releaseCandidate(ctx context.Context,schema int64)(bool,string,*time.Time,error){var build,status string;var required int64;var preflight *time.Time;err:=g.DB.QueryRow(ctx,`SELECT build_sha,status,required_schema_version,preflight_at FROM app_releases WHERE version=$1`,g.ReleaseVersion).Scan(&build,&status,&required,&preflight);if errors.Is(err,pgx.ErrNoRows){return false,"release manifest not found",nil,nil};if err!=nil{return false,"",nil,err};build=strings.ToLower(strings.TrimSpace(build));allowedStatus:=status=="STAGED"||status=="ACTIVE";pass:=build==g.GitCommit&&required==schema&&preflight!=nil&&allowedStatus;return pass,fmt.Sprintf("version=%s build_sha=%s expected_sha=%s required_schema=%d expected_schema=%d status=%s preflight=%v",g.ReleaseVersion,build,g.GitCommit,required,schema,status,preflight!=nil),preflight,nil}

func evidenceMaxAge(kind string)time.Duration{switch kind{case "BROWSER_SMOKE","SECURITY_REGRESSION":return 7*24*time.Hour;case "EDGE_TLS_PROXY","MTA_FLOW":return 24*time.Hour;default:return 0}}
func evidenceRequiresPostPreflight(kind string)bool{switch kind{case "BROWSER_SMOKE","SECURITY_REGRESSION","EDGE_TLS_PROXY","MTA_FLOW":return true;default:return false}}
func (g Gate) evidence(ctx context.Context,kind string,schema int64,now time.Time,notBefore *time.Time)(bool,string,error){var status,commit,releaseVersion,artifact,artifactSHA string;var recordedSchema int64;var completed time.Time;err:=g.DB.QueryRow(ctx,`SELECT status,git_commit,release_version,database_schema,artifact_ref,artifact_sha256,completed_at FROM commercial_readiness_evidence WHERE evidence_type=$1 AND git_commit=$2 AND database_schema=$3 AND release_version=$4 ORDER BY completed_at DESC,evidence_id DESC LIMIT 1`,kind,g.GitCommit,schema,g.ReleaseVersion).Scan(&status,&commit,&releaseVersion,&recordedSchema,&artifact,&artifactSHA,&completed);if errors.Is(err,pgx.ErrNoRows){return false,"missing PASS evidence for current release/commit/schema",nil};if err!=nil{return false,"",err};ageLimit:=evidenceMaxAge(kind);fresh:=!completed.After(now.Add(5*time.Minute))&&(ageLimit==0||now.Sub(completed.UTC())<=ageLimit);afterPreflight:=true;preflightDetail:="n/a";if notBefore!=nil{afterPreflight=!completed.Before(notBefore.UTC());preflightDetail=notBefore.UTC().Format(time.RFC3339)};artifact=strings.TrimSpace(artifact);artifactSHA=strings.ToLower(strings.TrimSpace(artifactSHA));metadataComplete:=artifact!=""&&sha256Pattern.MatchString(artifactSHA);return status=="PASS"&&fresh&&metadataComplete&&afterPreflight,fmt.Sprintf("status=%s release=%s commit=%s schema=%d artifact=%s artifact_sha256=%s artifact_metadata_complete=%v fresh=%v max_age=%s completed_at=%s release_preflight_at=%s after_preflight=%v",status,releaseVersion,commit,recordedSchema,artifact,artifactSHA,metadataComplete,fresh,ageLimit,completed.UTC().Format(time.RFC3339),preflightDetail,afterPreflight),nil}
func (g Gate) quality(ctx context.Context,now time.Time,schema int64)(bool,string,error){var pass bool;var completed time.Time;var failuresRaw []byte;var commit,releaseVersion,goldenHash,thresholdHash string;var recordedSchema int64;err:=g.DB.QueryRow(ctx,`SELECT gate_pass,completed_at,gate_failures,git_commit,release_version,database_schema,COALESCE(golden_sha256,''),COALESCE(thresholds_sha256,'') FROM quality_runs WHERE git_commit=$1 AND database_schema=$2 AND release_version=$3 ORDER BY completed_at DESC,run_id DESC LIMIT 1`,g.GitCommit,schema,g.ReleaseVersion).Scan(&pass,&completed,&failuresRaw,&commit,&releaseVersion,&recordedSchema,&goldenHash,&thresholdHash);if errors.Is(err,pgx.ErrNoRows){return false,"no quality run for current release/commit/schema",nil};if err!=nil{return false,"",err};var failures []string;_ = json.Unmarshal(failuresRaw,&failures);fresh:=now.Sub(completed.UTC())<=7*24*time.Hour&&completed.Before(now.Add(5*time.Minute));inputsBound:=sha256Pattern.MatchString(goldenHash)&&sha256Pattern.MatchString(thresholdHash);return pass&&fresh&&inputsBound,fmt.Sprintf("pass=%v release=%s commit=%s schema=%d inputs_bound=%v fresh_7d=%v completed_at=%s failures=%v",pass,releaseVersion,commit,recordedSchema,inputsBound,fresh,completed.UTC().Format(time.RFC3339),failures),nil}
func (g Gate) capacity(ctx context.Context,now time.Time,schema int64)(bool,string,error){var runID,snapshotID,measured int64;var completed time.Time;var hasADR bool;var commit,releaseVersion,recordedSchema string;err:=g.DB.QueryRow(ctx,`SELECT r.run_id,s.snapshot_id,s.measured_documents,r.completed_at,EXISTS(SELECT 1 FROM capacity_adr_decisions a WHERE a.snapshot_id=s.snapshot_id),COALESCE(r.config->>'git_commit',''),COALESCE(r.config->>'release_version',''),COALESCE(r.config->>'database_schema','') FROM capacity_benchmark_runs r JOIN capacity_snapshots s ON s.run_id=r.run_id WHERE r.status='COMPLETED' AND r.mode='ISOLATED_1M' AND s.measured_documents>=1000000 AND r.config->>'git_commit'=$1 AND r.config->>'database_schema'=$2 AND r.config->>'release_version'=$3 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(s.bottlenecks) AS b WHERE upper(COALESCE(b->>'severity',''))='HIGH') ORDER BY r.completed_at DESC,r.run_id DESC LIMIT 1`,g.GitCommit,fmt.Sprint(schema),g.ReleaseVersion).Scan(&runID,&snapshotID,&measured,&completed,&hasADR,&commit,&releaseVersion,&recordedSchema);if errors.Is(err,pgx.ErrNoRows){return false,"no acceptable ISOLATED_1M snapshot for current release/commit/schema with >=1,000,000 documents and no HIGH bottlenecks",nil};if err!=nil{return false,"",err};fresh:=now.Sub(completed.UTC())<=30*24*time.Hour&&completed.Before(now.Add(5*time.Minute));return hasADR&&fresh,fmt.Sprintf("run_id=%d snapshot_id=%d measured=%d release=%s commit=%s schema=%s adr=%v high_bottlenecks=0 fresh_30d=%v completed_at=%s",runID,snapshotID,measured,releaseVersion,commit,recordedSchema,hasADR,fresh,completed.UTC().Format(time.RFC3339)),nil}
func (g Gate) recovery(ctx context.Context,kind string,schema int64,now time.Time)(bool,string,error){var status,artifact,sha,commit,releaseVersion string;var recordedSchema,bytes,duration int64;var completed time.Time;err:=g.DB.QueryRow(ctx,`SELECT status,database_schema,completed_at,COALESCE(artifact_ref,''),COALESCE(artifact_sha256,''),COALESCE(artifact_bytes,0),COALESCE(duration_ms,0),COALESCE(git_commit,''),COALESCE(release_version,'') FROM recovery_drills WHERE drill_type=$1 AND git_commit=$2 AND database_schema=$3 AND release_version=$4 ORDER BY completed_at DESC,drill_id DESC LIMIT 1`,kind,g.GitCommit,schema,g.ReleaseVersion).Scan(&status,&recordedSchema,&completed,&artifact,&sha,&bytes,&duration,&commit,&releaseVersion);if errors.Is(err,pgx.ErrNoRows){return false,"no recovery drill for current release/commit/schema",nil};if err!=nil{return false,"",err};fresh:=now.Sub(completed.UTC())<=30*24*time.Hour&&completed.Before(now.Add(5*time.Minute));metadataComplete:=artifact!=""&&sha256Pattern.MatchString(sha)&&bytes>0&&duration>0&&commit==g.GitCommit&&releaseVersion==g.ReleaseVersion;return status=="PASS"&&recordedSchema==schema&&fresh&&metadataComplete,fmt.Sprintf("status=%s release=%s commit=%s schema=%d expected_schema=%d fresh_30d=%v artifact_metadata_complete=%v artifact=%s bytes=%d duration_ms=%d completed_at=%s",status,releaseVersion,commit,recordedSchema,schema,fresh,metadataComplete,artifact,bytes,duration,completed.UTC().Format(time.RFC3339)),nil}
func (g Gate) recoveryPair(ctx context.Context,schema int64)(bool,string,error){
	var backupSHA,restoreSHA,backupRef,restoreRef string
	q:=`SELECT COALESCE(artifact_sha256,''),COALESCE(artifact_ref,'') FROM recovery_drills WHERE drill_type=$1 AND status='PASS' AND git_commit=$2 AND database_schema=$3 AND release_version=$4 ORDER BY completed_at DESC,drill_id DESC LIMIT 1`
	if err:=g.DB.QueryRow(ctx,q,"BACKUP",g.GitCommit,schema,g.ReleaseVersion).Scan(&backupSHA,&backupRef);errors.Is(err,pgx.ErrNoRows){return false,"backup PASS evidence missing",nil}else if err!=nil{return false,"",err}
	if err:=g.DB.QueryRow(ctx,q,"RESTORE",g.GitCommit,schema,g.ReleaseVersion).Scan(&restoreSHA,&restoreRef);errors.Is(err,pgx.ErrNoRows){return false,"restore PASS evidence missing",nil}else if err!=nil{return false,"",err}
	backupSHA=strings.ToLower(strings.TrimSpace(backupSHA));restoreSHA=strings.ToLower(strings.TrimSpace(restoreSHA));same:=sha256Pattern.MatchString(backupSHA)&&backupSHA==restoreSHA
	return same,fmt.Sprintf("same_artifact=%v backup_ref=%s restore_ref=%s artifact_sha256=%s",same,backupRef,restoreRef,backupSHA),nil
}
func (g Gate) resourcePressure(ctx context.Context,now time.Time)(bool,string,error){var state string;var updated time.Time;err:=g.DB.QueryRow(ctx,`SELECT COALESCE(value->>'state',''),updated_at FROM system_settings WHERE key='resource_pressure'`).Scan(&state,&updated);if errors.Is(err,pgx.ErrNoRows){return false,"resource pressure state missing",nil};if err!=nil{return false,"",err};fresh:=now.Sub(updated.UTC())<=2*time.Minute&&updated.Before(now.Add(5*time.Minute));return fresh&&state!="CRITICAL"&&state!="",fmt.Sprintf("state=%s fresh_2m=%v updated_at=%s",state,fresh,updated.UTC().Format(time.RFC3339)),nil}
func (g Gate) mailDNS(ctx context.Context,now time.Time,domain,selector string)(bool,string,error){var ready,drift bool;var checked time.Time;var reasons []string;err:=g.DB.QueryRow(ctx,`SELECT ready,drift,reasons,checked_at FROM mail_dns_readiness_snapshots WHERE domain=$1 AND selector=$2 ORDER BY checked_at DESC,snapshot_id DESC LIMIT 1`,domain,selector).Scan(&ready,&drift,&reasons,&checked);if errors.Is(err,pgx.ErrNoRows){return false,"no mail DNS readiness snapshot for configured domain/selector",nil};if err!=nil{return false,"",err};fresh:=now.Sub(checked.UTC())<=30*time.Minute&&checked.Before(now.Add(5*time.Minute));return ready&&!drift&&fresh,fmt.Sprintf("domain=%s selector=%s ready=%v drift=%v fresh_30m=%v reasons=%v checked_at=%s",domain,selector,ready,drift,fresh,reasons,checked.UTC().Format(time.RFC3339)),nil}
