"use client";

import { FormEvent,useEffect,useState } from "react";
import { DeliveryStatusPanel, InternetAddressPanel } from "./InternetMailPanel";

type AccountUser={user_id:number;email:string;status:string};
type Mailbox={mailbox_id:number;address:string;status:string;storage_quota_bytes:number;storage_used_bytes:number};
type Recipient={address:string;type:string};
type Message={message_id:number;thread_id:number;subject:string;body_text:string;body_html?:string;provenance:string;state:string;sender_address:string;recipients?:Recipient[];sent_at?:string;created_at:string;updated_at:string};
type Item={mail_item_id:number;message:Message;folder:string;role:string;is_read:boolean;is_starred:boolean;created_at:string};
type Attachment={attachment_id:number;message_id:number;filename:string;byte_size:number;content_type:string;sha256:string};
type DraftEdit={message_id:number;thread_id:number;parent_message_id?:number;provenance:string;subject:string;body_text:string;recipients:Recipient[]};
const folders=["INBOX","SENT","DRAFTS","TRASH","SPAM"] as const;
const labels:Record<string,string>={INBOX:"Входящие",SENT:"Отправленные",DRAFTS:"Черновики",TRASH:"Корзина",SPAM:"Спам"};

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,credentials:"same-origin",cache:"no-store"});if(r.status===204)return undefined as T;const type=r.headers.get("content-type")||"";const data=type.includes("json")?await r.json().catch(()=>({})):await r.text();if(!r.ok)throw new Error(typeof data==="object"&&data?.error?data.error:`http_${r.status}`);return data as T}

export default function MailPage(){
 const[user,setUser]=useState<AccountUser|null>(null);const[mailbox,setMailbox]=useState<Mailbox|null>(null);const[csrf,setCSRF]=useState("");const[folder,setFolder]=useState("INBOX");const[items,setItems]=useState<Item[]>([]);const[selected,setSelected]=useState<Item|null>(null);const[compose,setCompose]=useState(false);const[composeSeed,setComposeSeed]=useState<Message|null>(null);const[composeDraft,setComposeDraft]=useState<Item|null>(null);const[search,setSearch]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(true);
 async function boot(){setLoading(true);try{const me=await api<{user:AccountUser}>("/api/account/me");const [box,token]=await Promise.all([api<Mailbox>("/api/mail/me"),api<{csrf_token:string}>("/api/account/csrf")]);setUser(me.user);setMailbox(box);setCSRF(token.csrf_token);setError("")}catch(e){setUser(null);setMailbox(null);setCSRF("");setError(e instanceof Error&&e.message!=="http_401"&&e.message!=="unauthorized"?e.message:"")}finally{setLoading(false)}}
 async function loadFolder(kind=folder){if(!user)return;try{const data=await api<{items:Item[]}>(`/api/mail/folders/${kind}?limit=100`);setItems(data.items||[]);setSelected(null);setError("")}catch(e){setError(e instanceof Error?e.message:"mail_unavailable")}}
 useEffect(()=>{void boot()},[]);useEffect(()=>{if(user)void loadFolder(folder)},[user,folder]);
 async function openItem(item:Item){try{const full=await api<Item>(`/api/mail/items/${item.mail_item_id}`);setSelected(full);if(!full.is_read&&full.folder!=="DRAFTS"){await mutate(`/api/mail/items/${full.mail_item_id}/read`,{value:true});full.is_read=true;setItems(v=>v.map(x=>x.mail_item_id===full.mail_item_id?{...x,is_read:true}:x))}}catch(e){setError(e instanceof Error?e.message:"not_found")}}
 async function mutate(url:string,payload?:unknown){return api<void>(url,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:payload===undefined?undefined:JSON.stringify(payload)})}
 async function runSearch(e:FormEvent){e.preventDefault();const q=search.trim();if(!q){void loadFolder();return}try{const data=await api<{items:Item[]}>(`/api/mail/search?q=${encodeURIComponent(q)}&limit=100`);setItems(data.items||[]);setSelected(null)}catch(e){setError(e instanceof Error?e.message:"search_failed")}}
 function openNew(){setComposeSeed(null);setComposeDraft(null);setCompose(true)}
 function openReply(kind:"REPLY"|"FORWARD",item:Item){setComposeDraft(null);setComposeSeed({...item.message,provenance:kind});setCompose(true)}
 function openDraft(item:Item){setComposeSeed(null);setComposeDraft(item);setCompose(true)}
 function closeCompose(){setCompose(false);setComposeSeed(null);setComposeDraft(null)}
 if(loading)return <main style={{padding:32}}>Загрузка почты…</main>;
 if(!user)return <MailAuth onSuccess={()=>void boot()} error={error}/>;
 return <main style={{height:"100vh",display:"grid",gridTemplateRows:"64px 1fr",background:"#f6f7f9",overflow:"hidden"}}>
  <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,padding:"0 20px",background:"white",borderBottom:"1px solid #e5e7eb"}}><div style={{display:"flex",alignItems:"center",gap:18}}><a href="/" style={{fontWeight:800,textDecoration:"none",letterSpacing:"-.02em"}}>ПОИСК</a><strong>Почта</strong></div><div style={{fontSize:13,color:"#5b6472",textAlign:"right"}}><div>{mailbox?.address}</div><div>{formatBytes(mailbox?.storage_used_bytes||0)} / {formatBytes(mailbox?.storage_quota_bytes||0)}</div></div></header>
  <div style={{display:"grid",gridTemplateColumns:"220px minmax(280px,420px) 1fr",minHeight:0}}>
   <aside style={{padding:16,borderRight:"1px solid #e5e7eb",background:"#fff",overflow:"auto"}}><button onClick={openNew} style={primary}>Написать</button><nav style={{display:"grid",gap:4,marginTop:16}}>{folders.map(f=><button key={f} onClick={()=>{setFolder(f);setSearch("")}} style={{...navBtn,background:folder===f?"#eef2ff":"transparent",fontWeight:folder===f?700:500}}>{labels[f]}</button>)}</nav><InternetAddressPanel csrf={csrf}/></aside>
   <section style={{borderRight:"1px solid #e5e7eb",background:"#fff",display:"grid",gridTemplateRows:"auto 1fr",minWidth:0}}><form onSubmit={runSearch} style={{padding:12,borderBottom:"1px solid #eee",display:"flex",gap:8}}><input value={search} onChange={e=>setSearch(e.target.value)} maxLength={256} placeholder="Поиск по письмам" style={input}/><button type="submit" style={smallBtn}>Найти</button></form><div style={{overflow:"auto"}}>{error&&<div style={{padding:12,color:"#991b1b"}}>{error}</div>}{items.length===0&&<div style={{padding:24,color:"#6b7280"}}>Нет писем</div>}{items.map(item=><button key={item.mail_item_id} onClick={()=>void openItem(item)} style={{width:"100%",display:"block",textAlign:"left",padding:"14px 16px",border:0,borderBottom:"1px solid #f0f0f0",background:selected?.mail_item_id===item.mail_item_id?"#f4f6fb":"white",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontWeight:item.is_read?600:800}}>{item.message.subject}</strong><small>{new Date(item.message.sent_at||item.created_at).toLocaleDateString()}</small></div><div style={{fontSize:13,color:"#4b5563",marginTop:4,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.message.sender_address}</div><div style={{fontSize:13,color:"#6b7280",marginTop:4,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.message.body_text}</div></button>)}</div></section>
   <section style={{minWidth:0,overflow:"auto",padding:24}}>{selected?<MessageView item={selected} csrf={csrf} onChanged={()=>void loadFolder()} onReply={(kind)=>openReply(kind,selected)} onEditDraft={()=>openDraft(selected)}/>:<div style={{height:"100%",display:"grid",placeItems:"center",color:"#9ca3af"}}>Выберите письмо</div>}</section>
  </div>
  {compose&&<ComposeModal csrf={csrf} seed={composeSeed} existingDraft={composeDraft} onClose={closeCompose} onSent={()=>{closeCompose();setFolder("SENT");void loadFolder("SENT")}} onSaved={()=>{if(folder==="DRAFTS")void loadFolder("DRAFTS")}}/>}
 </main>
}

function MailAuth({onSuccess,error}:{onSuccess:()=>void;error:string}){const[mode,setMode]=useState<"login"|"register">("login");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[localError,setLocalError]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/api/account/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});setLocalError("");onSuccess()}catch(e){setLocalError(e instanceof Error?e.message:"auth_failed")}finally{setBusy(false)}}return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:20,background:"#f7f7f8"}}><section style={{width:"min(430px,100%)",padding:28,border:"1px solid #e5e7eb",borderRadius:20,background:"white"}}><a href="/" style={{fontWeight:800,textDecoration:"none"}}>ПОИСК</a><h1 style={{fontSize:36,margin:"18px 0 8px"}}>Почта</h1><p style={{margin:"0 0 18px"}}>Почта пользователей ПОИСК: внутренняя доставка и, при подключённом шлюзе, интернет-письма.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,marginBottom:16}}><button onClick={()=>setMode("login")} style={smallBtn}>Войти</button><button onClick={()=>setMode("register")} style={smallBtn}>Регистрация</button></div><form onSubmit={submit} style={{display:"grid",gap:10}}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" required style={input}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Пароль" required style={input}/><button disabled={busy} style={primary}>{busy?"…":mode==="login"?"Войти":"Создать аккаунт"}</button></form>{(localError||error)&&<div style={{marginTop:12,color:"#991b1b"}}>{localError||error}</div>}</section></main>}

function MessageView({item,csrf,onChanged,onReply,onEditDraft}:{item:Item;csrf:string;onChanged:()=>void;onReply:(kind:"REPLY"|"FORWARD")=>void;onEditDraft:()=>void}){const[attachments,setAttachments]=useState<Attachment[]>([]);const[attachmentError,setAttachmentError]=useState("");useEffect(()=>{let cancelled=false;void api<{attachments:Attachment[]}>(`/api/mail/items/${item.mail_item_id}/attachments`).then(v=>{if(!cancelled){setAttachments(v.attachments||[]);setAttachmentError("")}}).catch(e=>{if(!cancelled){setAttachments([]);setAttachmentError(e instanceof Error?e.message:"attachments_unavailable")}});return()=>{cancelled=true}},[item.mail_item_id]);async function act(action:string,payload?:unknown){await api(`/api/mail/items/${item.mail_item_id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:payload===undefined?undefined:JSON.stringify(payload)});onChanged()}return <article style={{maxWidth:880,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><h2 style={{margin:"0 0 8px",fontSize:26}}>{item.message.subject}</h2><div style={{fontSize:13,color:"#4b5563"}}>От: {item.message.sender_address}</div>{item.message.recipients&&<div style={{fontSize:12,color:"#6b7280",marginTop:4}}>Кому: {item.message.recipients.map(r=>r.address).join(", ")}</div>}</div><button onClick={()=>void act("star",{value:!item.is_starred})} style={smallBtn}>{item.is_starred?"★":"☆"}</button></div><div style={{whiteSpace:"pre-wrap",lineHeight:1.65,marginTop:28,padding:"22px 0",borderTop:"1px solid #eee"}}>{item.message.body_text}</div>{attachments.length>0&&<div style={{display:"grid",gap:7,padding:"14px 0",borderTop:"1px solid #eee"}}><strong>Вложения</strong>{attachments.map(a=><a key={a.attachment_id} href={`/api/mail/attachments/${a.attachment_id}`} style={{display:"flex",justifyContent:"space-between",gap:12,color:"#1d4ed8"}}><span>{a.filename}</span><span>{formatBytes(a.byte_size)}</span></a>)}</div>}{attachmentError&&<div style={{fontSize:12,color:"#991b1b"}}>{attachmentError}</div>}{item.folder==="SENT"&&<DeliveryStatusPanel messageID={item.message.message_id}/>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:18}}>{item.folder==="DRAFTS"?<button style={primary} onClick={onEditDraft}>Редактировать</button>:<><button style={smallBtn} onClick={()=>onReply("REPLY")}>Ответить</button><button style={smallBtn} onClick={()=>onReply("FORWARD")}>Переслать</button></>}{item.folder==="TRASH"?<button style={smallBtn} onClick={()=>void act("restore")}>Восстановить</button>:<button style={smallBtn} onClick={()=>void act("trash")}>В корзину</button>}{item.role==="DELIVERY"&&item.folder!=="TRASH"&&<button style={smallBtn} onClick={()=>void act("spam",{value:item.folder!=="SPAM"})}>{item.folder==="SPAM"?"Не спам":"Спам"}</button>}</div></article>}

function ComposeModal({csrf,seed,existingDraft,onClose,onSent,onSaved}:{csrf:string;seed:Message|null;existingDraft:Item|null;onClose:()=>void;onSent:()=>void;onSaved:()=>void}){
 const initialProvenance=existingDraft?.message.provenance||((seed?.provenance==="REPLY"||seed?.provenance==="FORWARD")?seed.provenance:"COMPOSE");
 const[provenance,setProvenance]=useState(initialProvenance);const[parent,setParent]=useState<number|null>(existingDraft?null:(initialProvenance==="COMPOSE"?null:seed?.message_id||null));const[to,setTo]=useState(existingDraft?.message.recipients?.map(r=>r.address).join(", ")||(initialProvenance==="REPLY"&&seed?seed.sender_address:""));const[subject,setSubject]=useState(existingDraft?.message.subject||(seed?(initialProvenance==="FORWARD"?`Fwd: ${seed.subject}`:initialProvenance==="REPLY"?`Re: ${seed.subject}`:seed.subject):""));const[body,setBody]=useState(existingDraft?.message.body_text||(initialProvenance==="FORWARD"&&seed?`\n\n--- Пересланное сообщение ---\n${seed.body_text}`:""));const[draftID,setDraftID]=useState<number|null>(existingDraft?.message.message_id||null);const[attachments,setAttachments]=useState<Attachment[]>([]);const[busy,setBusy]=useState(false);const[loadingDraft,setLoadingDraft]=useState(Boolean(existingDraft));const[error,setError]=useState("");
 useEffect(()=>{if(!existingDraft)return;let cancelled=false;setLoadingDraft(true);Promise.all([api<DraftEdit>(`/api/mail/drafts/${existingDraft.message.message_id}`),api<{attachments:Attachment[]}>(`/api/mail/items/${existingDraft.mail_item_id}/attachments`)]).then(([draft,files])=>{if(cancelled)return;setProvenance(draft.provenance);setParent(draft.parent_message_id||null);setTo((draft.recipients||[]).map(r=>r.address).join(", "));setSubject(draft.subject);setBody(draft.body_text);setDraftID(draft.message_id);setAttachments(files.attachments||[]);setError("")}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"draft_load_failed")}).finally(()=>{if(!cancelled)setLoadingDraft(false)});return()=>{cancelled=true}},[existingDraft?.message.message_id]);
 const payload=()=>({subject,body_text:body,recipients:to.split(/[,;]+/).map(v=>v.trim()).filter(Boolean).map(address=>({address,type:"TO"})),provenance,parent_message_id:parent});
 async function save(){if(loadingDraft)return null;setBusy(true);try{const data=draftID?await api<Message>(`/api/mail/drafts/${draftID}`,{method:"PUT",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify(payload())}):await api<Message>("/api/mail/drafts",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify(payload())});setDraftID(data.message_id);setError("");onSaved();return data.message_id}catch(e){setError(e instanceof Error?e.message:"draft_failed");return null}finally{setBusy(false)}}
 async function send(){const id=await save();if(!id)return;setBusy(true);try{await api(`/api/mail/drafts/${id}/send`,{method:"POST",headers:{"X-CSRF-Token":csrf}});onSent()}catch(e){setError(e instanceof Error?e.message:"send_failed")}finally{setBusy(false)}}
 async function upload(file:File){let id=draftID;if(!id)id=await save();if(!id)return;const form=new FormData();form.append("file",file);try{const out=await api<Attachment>(`/api/mail/drafts/${id}/attachments`,{method:"POST",headers:{"X-CSRF-Token":csrf},body:form});setAttachments(v=>[...v,out]);setError("")}catch(e){setError(e instanceof Error?e.message:"upload_failed")}}
 async function detach(a:Attachment){if(!draftID)return;try{await api<void>(`/api/mail/drafts/${draftID}/attachments/${a.attachment_id}`,{method:"DELETE",headers:{"X-CSRF-Token":csrf}});setAttachments(v=>v.filter(x=>x.attachment_id!==a.attachment_id));setError("")}catch(e){setError(e instanceof Error?e.message:"detach_failed")}}
 return <div style={{position:"fixed",zIndex:20,inset:0,background:"rgba(0,0,0,.35)",display:"grid",placeItems:"center",padding:16}}><section style={{width:"min(760px,100%)",maxHeight:"92vh",overflow:"auto",background:"white",borderRadius:18,padding:20,boxShadow:"0 24px 70px rgba(0,0,0,.25)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong>{existingDraft?"Редактировать черновик":"Новое письмо"}</strong><button onClick={onClose} style={smallBtn}>×</button></div>{loadingDraft?<div style={{padding:"24px 0"}}>Загрузка черновика…</div>:<div style={{display:"grid",gap:9,marginTop:16}}><input value={to} onChange={e=>setTo(e.target.value)} placeholder="Кому: email или внутренний адрес" style={input}/><input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={998} placeholder="Тема" style={input}/><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={200000} placeholder="Текст письма" style={{...input,minHeight:260,resize:"vertical"}}/><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><label style={smallBtn as React.CSSProperties}>Прикрепить<input type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label><div style={{display:"flex",gap:8}}><button disabled={busy} onClick={()=>void save()} style={smallBtn}>Сохранить</button><button disabled={busy} onClick={()=>void send()} style={primary}>Отправить</button></div></div>{attachments.length>0&&<div style={{display:"grid",gap:6}}>{attachments.map(a=><div key={a.attachment_id} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,fontSize:13}}><span>{a.filename} · {formatBytes(a.byte_size)}</span><button type="button" style={smallBtn} onClick={()=>void detach(a)}>Удалить</button></div>)}</div>}{error&&<div style={{color:"#991b1b"}}>{error}</div>}</div>}</section></div>
}

function formatBytes(v:number){if(v<1024)return `${v} B`;if(v<1024*1024)return `${(v/1024).toFixed(1)} KB`;return `${(v/1024/1024).toFixed(1)} MB`}
const input:React.CSSProperties={width:"100%",minWidth:0,padding:"10px 12px",border:"1px solid #d1d5db",borderRadius:10,background:"white",font:"inherit"};const primary:React.CSSProperties={border:0,borderRadius:10,padding:"11px 16px",background:"#111827",color:"white",fontWeight:700,cursor:"pointer"};const smallBtn:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:9,padding:"8px 11px",background:"white",cursor:"pointer",font:"inherit"};const navBtn:React.CSSProperties={border:0,borderRadius:9,padding:"10px 12px",textAlign:"left",cursor:"pointer",font:"inherit"};