"use client";

import { useEffect,useState } from "react";

type AdminMe={admin_id:number;email:string;role:string;expires_at:string};
type Diagnostics={
 crawler:{domains:number;urls:number;ready:number;leased:number;retry:number;dead:number;success_24h:number;retry_24h:number;dead_24h:number;blocked_24h:number};
 index:{ready:number;leased:number;retry:number;dead:number;processed_24h:number;indexed_urls:number;excluded_urls:number;error_urls:number;average_quality:number;average_spam:number};
 demand:{watch:number;open:number;resolved:number;suppressed:number;active_feedback:number};
 webmaster:{users:number;sites:number;pending_verifications:number;queued_sitemaps:number;queued_url_requests:number};
 billing:{accounts:number;active_subscriptions:number;past_due_subscriptions:number;open_invoices:number;failed_invoices:number;unprocessed_payment_events:number};
 data_hub:{draft:number;published:number;suppressed:number;publication_events_24h:number;trends_today:number};
 mail:{active_mailboxes:number;disabled_mailboxes:number;draft_messages:number;sent_messages:number;inbox_items:number;spam_items:number;trash_items:number;attachment_bytes:number;blob_gc_backlog:number;send_events_24h:number};
 capacity?:{snapshot_id:number;measured_documents:number;measured_at:string};
};
type Quality={run_id:number;queries:number;ndcg_10:number;mrr:number;recall_10:number;zero_result_rate:number;duplicate_10:number;gate_pass:boolean;failures:string[];source:string;completed_at:string};
type RecoveryDrill={drill_id:number;status:string;artifact_ref?:string;artifact_bytes?:number;duration_ms?:number;database_schema:number;completed_at:string};
type Recovery={database_schema:number;active_release?:{version:string;build_sha:string;status:string;required_schema:number;map_version?:string};previous_release?:{version:string;build_sha:string;status:string;required_schema:number};latest_backup?:RecoveryDrill;latest_restore?:RecoveryDrill;ready:boolean;reasons?:string[]};
type AnswerMetrics={requests:number;available:number;fallback_low_confidence:number;fallback_insufficient_sources:number;fallback_other:number;errors:number;average_confidence:number};
type MapState={active?:{version:string;status:string;pmtiles_size:number;pmtiles_sha256:string;style_sha256:string;min_zoom:number;max_zoom:number;created_at:string};previous?:{version:string};activated_at?:string;updated_at:string};
type AddressData={active_addresses:number;inactive_addresses:number;orphan_addresses:number;ignored_addresses:number;latest_batch_id?:number;latest_revision?:string;latest_batch_status?:string;staged_count:number;rejected_count:number;applied_count:number;updated_at?:string};
const card:React.CSSProperties={border:"1px solid #e2e2e2",borderRadius:12,padding:16,background:"#fff"};
async function read<T>(url:string):Promise<T>{const r=await fetch(url,{cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`http_${r.status}`);return d as T}
function bytes(v:number){if(v<1024)return `${v} B`;if(v<1048576)return `${(v/1024).toFixed(1)} KB`;if(v<1073741824)return `${(v/1048576).toFixed(1)} MB`;return `${(v/1073741824).toFixed(2)} GB`}
export default function SystemPage(){
 const[me,setMe]=useState<AdminMe|null>(null);const[d,setD]=useState<Diagnostics|null>(null);const[quality,setQuality]=useState<Quality|null>(null);const[recovery,setRecovery]=useState<Recovery|null>(null);const[answer,setAnswer]=useState<AnswerMetrics|null>(null);const[map,setMap]=useState<MapState|null>(null);const[address,setAddress]=useState<AddressData|null>(null);const[error,setError]=useState("");
 async function load(){try{const[m,diag,q,rec,ans,mapState,addr]=await Promise.all([read<AdminMe>("/api/admin/me"),read<Diagnostics>("/api/admin/diagnostics"),read<{latest:Quality|null}>("/api/admin/quality/latest"),read<Recovery>("/api/admin/recovery"),read<AnswerMetrics>("/api/admin/answer/metrics?hours=24"),read<MapState>("/api/admin/maps/state"),read<AddressData>("/api/admin/addresses/data")]);setMe(m);setD(diag);setQuality(q.latest);setRecovery(rec);setAnswer(ans);setMap(mapState);setAddress(addr);setError("")}catch(e){setError(e instanceof Error?e.message:"unavailable")}}
 useEffect(()=>{void load()},[]);
 if(error)return <main style={{maxWidth:1100,margin:"40px auto",padding:24}}><a href="/admin">← Admin</a><h1>System diagnostics</h1><p>{error}</p></main>;
 if(!me||!d)return <main style={{maxWidth:1100,margin:"40px auto",padding:24}}>Загрузка…</main>;
 return <main style={{maxWidth:1180,margin:"32px auto",padding:24,display:"grid",gap:16}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><a href="/admin">← Admin</a><h1 style={{margin:"8px 0 0"}}>System diagnostics</h1><small>{me.email} · {me.role}</small></div><button onClick={()=>void load()}>Обновить</button></header>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12}}>
   <section style={card}><strong>Web index</strong><div>Indexed {d.index.indexed_urls.toLocaleString("ru-RU")}</div><div>Excluded {d.index.excluded_urls} · error {d.index.error_urls}</div><div>Quality {d.index.average_quality.toFixed(1)} · spam {d.index.average_spam.toFixed(1)}</div><div>Outbox ready {d.index.ready} · retry {d.index.retry} · dead {d.index.dead}</div></section>
   <section style={card}><strong>Crawler</strong><div>{d.crawler.domains} domains · {d.crawler.urls} URLs</div><div>24h success {d.crawler.success_24h}</div><div>retry {d.crawler.retry_24h} · dead {d.crawler.dead_24h} · blocked {d.crawler.blocked_24h}</div></section>
   <section style={card}><strong>Demand</strong><div>open {d.demand.open} · watch {d.demand.watch}</div><div>resolved {d.demand.resolved} · suppressed {d.demand.suppressed}</div><div>active feedback {d.demand.active_feedback}</div></section>
   <section style={card}><strong>Data Hub</strong><div>published {d.data_hub.published} · draft {d.data_hub.draft}</div><div>suppressed {d.data_hub.suppressed}</div><div>events 24h {d.data_hub.publication_events_24h} · trends today {d.data_hub.trends_today}</div></section>
   <section style={card}><strong>Webmaster</strong><div>{d.webmaster.users} users · {d.webmaster.sites} sites</div><div>pending verification {d.webmaster.pending_verifications}</div><div>sitemaps {d.webmaster.queued_sitemaps} · URL ops {d.webmaster.queued_url_requests}</div></section>
   <section style={card}><strong>Billing</strong><div>{d.billing.active_subscriptions} active subscriptions</div><div>past due {d.billing.past_due_subscriptions}</div><div>open invoices {d.billing.open_invoices} · failed {d.billing.failed_invoices}</div><div>unprocessed events {d.billing.unprocessed_payment_events}</div></section>
   <section style={{...card,borderColor:d.mail.blob_gc_backlog>100?"#f0c36d":"#e2e2e2"}}><strong>Mail</strong><div>{d.mail.active_mailboxes} active mailboxes · {d.mail.disabled_mailboxes} disabled</div><div>{d.mail.sent_messages.toLocaleString("ru-RU")} sent · {d.mail.draft_messages} drafts · {d.mail.send_events_24h} sends/24h</div><div>Inbox {d.mail.inbox_items} · spam {d.mail.spam_items} · trash {d.mail.trash_items}</div><div>Attachments {bytes(d.mail.attachment_bytes)} · GC backlog {d.mail.blob_gc_backlog}</div></section>
  </div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}>
   <section style={{...card,borderColor:quality?.gate_pass?"#a8d5a2":"#e4b2b2"}}><strong>Search Quality</strong>{quality?<><div>Gate: {quality.gate_pass?"PASS":"FAIL"} · {new Date(quality.completed_at).toLocaleString()}</div><div>{quality.queries} queries · NDCG@10 {quality.ndcg_10.toFixed(3)} · MRR {quality.mrr.toFixed(3)}</div><div>Recall@10 {quality.recall_10.toFixed(3)} · zero {(quality.zero_result_rate*100).toFixed(1)}% · dup {(quality.duplicate_10*100).toFixed(1)}%</div>{quality.failures?.length?<div>Failures: {quality.failures.join("; ")}</div>:null}</>:<div>Quality run ещё не зафиксирован.</div>}</section>
   <section style={card}><strong>Answer Engine · 24h</strong>{answer?<><div>{answer.requests} requests · {answer.available} available · {answer.errors} errors</div><div>low confidence {answer.fallback_low_confidence} · insufficient sources {answer.fallback_insufficient_sources}</div><div>average confidence {answer.average_confidence.toFixed(3)}</div></>:<div>Нет данных.</div>}</section>
   <section style={{...card,borderColor:recovery?.ready?"#a8d5a2":"#f0c36d"}}><strong>Release / Recovery</strong>{recovery?<><div>Ready: {recovery.ready?"YES":"NO"} · DB schema {recovery.database_schema}</div><div>Active: {recovery.active_release?.version||"нет"} · previous {recovery.previous_release?.version||"нет"}</div><div>Backup: {recovery.latest_backup?.status||"нет evidence"} · Restore: {recovery.latest_restore?.status||"нет evidence"}</div>{recovery.reasons?.length?<div>Blockers: {recovery.reasons.join(", ")}</div>:null}</>:null}</section>
   <section style={card}><strong>Maps</strong><div>Active: {map?.active?.version||"не активирована"}</div><div>Previous: {map?.previous?.version||"нет"}</div>{map?.active?<><div>PMTiles {(map.active.pmtiles_size/1048576).toFixed(1)} MB · zoom {map.active.min_zoom}-{map.active.max_zoom}</div><div style={{wordBreak:"break-all",fontSize:12}}>sha256 {map.active.pmtiles_sha256}</div></>:null}</section>
   <section style={card}><strong>Address data</strong>{address?<><div>{address.active_addresses.toLocaleString("ru-RU")} active · {address.inactive_addresses.toLocaleString("ru-RU")} inactive</div><div>orphans {address.orphan_addresses} · ignored {address.ignored_addresses}</div><div>revision {address.latest_revision||"нет"} · batch {address.latest_batch_id||"—"} · {address.latest_batch_status||"—"}</div><div>applied {address.applied_count} · rejected {address.rejected_count}</div></>:null}</section>
  </div>
  <section style={card}><strong>Capacity</strong>{d.capacity?<><div>Snapshot #{d.capacity.snapshot_id}</div><div>Measured documents {d.capacity.measured_documents.toLocaleString("ru-RU")}</div><div>{new Date(d.capacity.measured_at).toLocaleString()}</div></>:<div>Нет измеренного Capacity snapshot — коммерческий gate не закрыт.</div>}</section>
 </main>
}
