"use client";

import { useEffect,useState } from "react";

type AdminMe={admin_id:number;email:string;role:string;expires_at:string};
type Batch={batch_id:number;source_key:string;external_batch_key:string;mode:string;status:string;row_count:number;staged_count:number;rejected_count:number;applied_count:number;checkpoint_row:number;last_error?:string;updated_at:string};
type Review={review_id:number;batch_id:number;staging_id:number;candidate_place_id:number;candidate_name:string;incoming_name:string;incoming_address?:string;candidate_address?:string;reason_code:string;score:number;status:string;created_at:string};
type Preview={preview_token:string;expires_at:string;review:Review;decision:string;reason:string};
const card:React.CSSProperties={border:"1px solid #e2e2e2",borderRadius:12,padding:16,background:"#fff"};
async function read<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`http_${r.status}`);return d as T}
export default function OrganizationsAdmin(){
 const[me,setMe]=useState<AdminMe|null>(null);const[csrf,setCSRF]=useState("");const[batches,setBatches]=useState<Batch[]>([]);const[reviews,setReviews]=useState<Review[]>([]);const[selected,setSelected]=useState<Review|null>(null);const[decision,setDecision]=useState("MERGE");const[reason,setReason]=useState("Проверено оператором");const[preview,setPreview]=useState<Preview|null>(null);const[error,setError]=useState("");
 const operator=me?.role==="OPERATOR"||me?.role==="SUPERADMIN";
 async function load(){try{const[m,c,b,r]=await Promise.all([read<AdminMe>("/api/admin/me"),read<{csrf_token:string}>("/api/admin/csrf"),read<{results:Batch[]}>("/api/admin/organizations/imports?limit=100"),read<{results:Review[]}>("/api/admin/organizations/reviews?status=OPEN&limit=100")]);setMe(m);setCSRF(c.csrf_token);setBatches(b.results);setReviews(r.results);setError("")}catch(e){setError(e instanceof Error?e.message:"unavailable")}}
 useEffect(()=>{void load()},[]);
 async function makePreview(){if(!selected||!operator)return;try{const p=await read<Preview>("/api/admin/organizations/reviews/preview",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({review_id:selected.review_id,decision,reason})});setPreview(p);setError("")}catch(e){setError(e instanceof Error?e.message:"preview_failed")}}
 async function apply(){if(!preview||!operator)return;try{await read("/api/admin/organizations/reviews/apply",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({preview_token:preview.preview_token})});setPreview(null);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"apply_failed")}}
 return <main style={{maxWidth:1200,margin:"32px auto",padding:24,display:"grid",gap:16}}><header><a href="/admin">← Admin</a><h1>Organizations / imports</h1>{me&&<small>{me.email} · {me.role}</small>}</header>{error&&<div style={{...card,borderColor:"#b00"}}>{error}</div>}
 <section style={card}><h2>Import batches</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">ID</th><th align="left">Source</th><th>Status</th><th>Mode</th><th>Rows</th><th>Applied</th><th>Rejected</th><th align="left">Updated</th></tr></thead><tbody>{batches.map(b=><tr key={b.batch_id}><td>{b.batch_id}</td><td>{b.source_key}<div style={{fontSize:12,color:"#666"}}>{b.external_batch_key}</div></td><td align="center">{b.status}</td><td align="center">{b.mode}</td><td align="center">{b.row_count}</td><td align="center">{b.applied_count}</td><td align="center">{b.rejected_count}</td><td>{new Date(b.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section style={card}><h2>Open merge reviews</h2><div style={{display:"grid",gap:8}}>{reviews.map(r=><button key={r.review_id} onClick={()=>{setSelected(r);setPreview(null);setDecision("MERGE")}} style={{textAlign:"left",padding:12,border:"1px solid #ddd",borderRadius:10,background:selected?.review_id===r.review_id?"#eee":"white"}}><strong>#{r.review_id} · score {r.score}</strong><div>Incoming: {r.incoming_name} · {r.incoming_address||"без адреса"}</div><div>Candidate: {r.candidate_name} · {r.candidate_address||"без адреса"}</div><small>{r.reason_code}</small></button>)}</div></section>
 {selected&&<section style={card}><h2>Review #{selected.review_id}</h2>{operator?<><div style={{display:"grid",gridTemplateColumns:"180px 1fr auto",gap:8}}><select value={decision} onChange={e=>{setDecision(e.target.value);setPreview(null)}}><option value="MERGE">MERGE</option><option value="CREATE_NEW">CREATE_NEW</option><option value="REJECT">REJECT</option></select><input value={reason} onChange={e=>{setReason(e.target.value);setPreview(null)}} placeholder="Причина решения"/><button onClick={()=>void makePreview()}>Preview</button></div>{preview&&<div style={{marginTop:12,padding:12,border:"1px solid #d99",borderRadius:10}}><strong>Подтверждение</strong><div>{preview.decision}: {preview.review.incoming_name} → {preview.review.candidate_name}</div><div>Причина: {preview.reason}</div><div>Истекает: {new Date(preview.expires_at).toLocaleString()}</div><button style={{marginTop:10}} onClick={()=>void apply()}>Apply decision</button></div>}</>:<p>Read-only роль: решение review недоступно.</p>}</section>}
 </main>
}
